# Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix


# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense



Using TensorFlow backend.


#  Preprocessing data

In [2]:
# Importing the dataset using pandas
cars = pd.read_csv('car.csv')
cars.head()


buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [3]:
# Create matrix of features and matrix of target variable.
X = cars.iloc[:, 0:6].values
y = cars.iloc[:, 6:7].values 
cars.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

# Encoding data

In [4]:
labelencoder_X_0 = LabelEncoder()
X[:, 0] = labelencoder_X_0.fit_transform(X[:, 0])
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
labelencoder_X_3 = LabelEncoder()
X[:, 3] = labelencoder_X_3.fit_transform(X[:, 3])
labelencoder_X_4 = LabelEncoder()
X[:, 4] = labelencoder_X_4.fit_transform(X[:, 4])
labelencoder_X_5 = LabelEncoder()
X[:, 5] = labelencoder_X_5.fit_transform(X[:, 5])

labelencoder_y_0 = LabelEncoder()
y[:,0] = labelencoder_y_0.fit_transform(y[:,0])

y[:]

array([[2],
       [2],
       [2],
       ..., 
       [2],
       [1],
       [3]], dtype=object)

In [5]:
cars.head()

buying maint doors persons lug_boot safety class
0      3     3     0       0        2      1     2
1      3     3     0       0        2      2     2
2      3     3     0       0        2      0     2
3      3     3     0       0        1      1     2
4      3     3     0       0        1      2     2

In [6]:
onehotencoder = OneHotEncoder(categorical_features = "all")
X = onehotencoder.fit_transform(X).toarray()

onehotencoder = OneHotEncoder(categorical_features = "all")
y = onehotencoder.fit_transform(y).toarray()

In [7]:
cars.head()

buying maint doors persons lug_boot safety class
0      3     3     0       0        2      1     2
1      3     3     0       0        2      2     2
2      3     3     0       0        2      0     2
3      3     3     0       0        1      1     2
4      3     3     0       0        1      2     2

In [8]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [9]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Creating NN and training it

In [10]:
#Initializing Neural Network
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 21))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

C:\Users\alaa\Anaconda3\envs\DL\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=21, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\alaa\Anaconda3\envs\DL\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=10, kernel_initializer="uniform")`
  
C:\Users\alaa\Anaconda3\envs\DL\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=4, kernel_initializer="uniform")`
  


In [11]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
1382/1382 [==============================] - 2s 1ms/step - loss: 0.4830 - acc: 0.7784
Epoch 2/100
1382/1382 [==============================] - 0s 117us/step - loss: 0.2632 - acc: 0.8924
Epoch 3/100
1382/1382 [==============================] - 0s 116us/step - loss: 0.2175 - acc: 0.9092
Epoch 4/100
1382/1382 [==============================] - 0s 115us/step - loss: 0.1927 - acc: 0.9159
Epoch 5/100
1382/1382 [==============================] - 0s 110us/step - loss: 0.1770 - acc: 0.9159
Epoch 6/100
1382/1382 [==============================] - 0s 153us/step - loss: 0.1660 - acc: 0.9175
Epoch 7/100
1382/1382 [==============================] - 0s 126us/step - loss: 0.1573 - acc: 0.9181
Epoch 8/100
1382/1382 [==============================] - 0s 138us/step - loss: 0.1502 - acc: 0.9181
Epoch 9/100
1382/1382 [==============================] - 0s 128us/step - loss: 0.1426 - acc: 0.9285
Epoch 10/100
1382/1382 [==============================] - 0s 118us/step - loss: 0.1356 - acc: 0.9584
E

1382/1382 [==============================] - 0s 96us/step - loss: 0.0368 - acc: 0.9792
Epoch 83/100
1382/1382 [==============================] - 0s 95us/step - loss: 0.0363 - acc: 0.9790
Epoch 84/100
1382/1382 [==============================] - 0s 104us/step - loss: 0.0358 - acc: 0.9792
Epoch 85/100
1382/1382 [==============================] - 0s 116us/step - loss: 0.0360 - acc: 0.9790
Epoch 86/100
1382/1382 [==============================] - 0s 102us/step - loss: 0.0359 - acc: 0.9787
Epoch 87/100
1382/1382 [==============================] - 0s 100us/step - loss: 0.0360 - acc: 0.9788
Epoch 88/100
1382/1382 [==============================] - 0s 100us/step - loss: 0.0358 - acc: 0.9787
Epoch 89/100
1382/1382 [==============================] - 0s 99us/step - loss: 0.0356 - acc: 0.9792
Epoch 90/100
1382/1382 [==============================] - 0s 106us/step - loss: 0.0358 - acc: 0.9792
Epoch 91/100
1382/1382 [==============================] - 0s 116us/step - loss: 0.0362 - acc: 0.9788
Epoch 

In [13]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)
print(y_test)

[[False False  True False]
 [False False  True False]
 [False False  True False]
 ..., 
 [False False  True False]
 [False False  True False]
 [False False  True False]]
[[ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 ..., 
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]]


# Creating the Confusion Matrix

In [14]:
cm = confusion_matrix(y_test.flatten(), y_pred.flatten())
print(cm)

[[1031    7]
 [  34  312]]


In [15]:
# Accuracy of our model
accuracy = (cm[0,0]+cm[1,1]) * 100/ cm.sum()
print("The accuracy of our model is %2.1f %%" % accuracy)

The accuracy of our model is 97.0 %
